/* Problem 2: Even Fibonacci Numbers
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the
first 10 terms will be:
  1, 2, 3, 5, 8, 13, 21, 34, 55, 39, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
even-valued terms.
*/
object Problem002 extends App {
	def fibonacci: LazyList[Int] =
		def loop(a: Int, b: Int): LazyList[Int] = (a + b) #:: loop(b, a + b)
		loop(0, 1)
	
	val answer = fibonacci.takeWhile(_ <= 4_000_000).filter(_ % 2 == 0).sum
	println(answer)
}