/* Problem 44: Pentagonal Numbers
Pentagonal numbers are generated by the formula, P[n]=n*(3*n−1)/2. The
first ten pentagonal numbers are:
  1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P[4] + P[7] = 22 + 70 = 92 = P[8]. However, their
difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, P[j] and P[k], for which their sum and
difference are pentagonal and D = |P[k] − P[j]| is minimised; what is the
value of D?
*/
object Problem044 extends App {
	def pentagonal(n: Int) = n * (3 * n - 1) / 2
	
	val isPentagonal = (Iterator from 1).map(pentagonal).takeWhile(_ > 0).toSet
	
	def minimumDifference =
		var result = Int.MaxValue
		for k <- 2 to isPentagonal.size do
			val pk = pentagonal(k)
			val js = k - 1 to 1 by -1
			for pj <- js.map(pentagonal).takeWhile(pk - _ < result) do
				if isPentagonal(pj + pk) && isPentagonal(pk - pj) then
					result = pk - pj
		result
	
	println(minimumDifference)
}