/* Problem 45: Triangular, Pentagonal, & Hexagonal
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
  Triangle	 	T[n]=n(n+1)/2	 	1, 3, 6, 10, 15, ...
  Pentagonal	P[n]=n(3n−1)/2	1, 5, 12, 22, 35, ...
  Hexagonal	 	H[n]=n(2n−1)	 	1, 6, 15, 28, 45, ...

It can be verified that T[285] = P[165] = H[143] = 40755.
Find the next triangle number that is also pentagonal and hexagonal.
*/

import Math.sqrt

object Problem045 extends App {
	val hexagonals = (LazyList from 144).map(n => n.toLong * (2 * n - 1))
	
	def isPentagonal(x: Long) = sqrt(24 * x + 1) % 6 == 5.0
	
	val answer = hexagonals.find(isPentagonal).get
	println(answer)
}
